from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/logout/", views.logout_view, name="logout"),
    path('logout/', views.logout_view, name='logout'),
    path('varun1/', views.varun1_view, name='varun1'),
    path('varun2', views.varun2_view, name='varun2'),
    path('varun3/', views.varun3_view, name='varun3'),
    path('varun4/', views.varun4_view, name='varun4'),
    path('varun5/', views.varun5_view, name='varun5'),
    path('varun6/', views.varun6_view, name='varun6'),
    path('varun7/', views.varun7_view, name='varun7'),
    path('varun8/', views.varun8_view, name='varun8'),
    path('varun9/', views.varun9_view, name='varun9'),
    path('varun10/', views.varun10_view, name='varun10'),
    path('varun11/', views.varun11_view, name='varun11'),
    path('varun12/', views.varun12_view, name='varun12'),
    path('varun13/', views.varun13_view, name='varun13'),
    path('varun14/', views.varun14_view, name='varun14'),
    path('varun15/', views.varun15_view, name='varun15'),
    path('varun16/', views.varun16_view, name='varun16'),
    path('varun17/', views.varun17_view, name='varun17'),
    path('varun18/', views.varun18_view, name='varun18'),
    path('varun19/', views.varun19_view, name='varun19'),
    path('varun20/', views.varun20_view, name='varun20'),
    path('varun21/', views.varun21_view, name='varun21'),
    path('varun22/', views.varun22_view, name='varun22'),
    path('varun23/', views.varun23_view, name='varun23'),
    path('varun24/', views.varun24_view, name='varun24'),
    path('varun25/', views.varun25_view, name='varun25'),
    path('varun26/', views.varun26_view, name='varun26'),
    path('varun27/', views.varun27_view, name='varun27'),
    path('varun28/', views.varun28_view, name='varun28'),
    path('varun29/', views.varun29_view, name='varun29'),
    path('varun30/', views.varun30_view, name='varun30'),
    path('add/', views.add_view, name='add'),
    path('sub/', views.sub_view, name='sub'),
    path('multiply/', views.multiply_view, name='multiply'),
    path('sqrt/', views.sqrt_view, name='sqrt'),
    path('division/', views.division_view, name='division'),
    path('power/', views.power_view, name='power')

]
